battle:
  max_turns: 3
  turn_timeout: 30  # seconds
  battle_timeout: 300  # seconds
  token_limit: 100
  cooldown: 30  # seconds between battles

rating:
  initial: 1200
  k_factor: 32
  provisional_k: 64
  min_rating: 100
  max_rating: 3000
  provisional_battles: 10

limits:
  battles_per_hour: 10
  battles_per_day: 100
  prompts_per_day: 5
  edits_per_hour: 3 